version: '3.9'
services:
  # Web servisi tanımı
  web:
    build: .
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - backend

  # Veritabanı servisi tanımı
  db:
    build: ./db/
    image: mysql:latest
    environment:
      MYSQL_DATABASE: person_count_database2
      MYSQL_ROOT_PASSWORD: Beytullah.123 
    ports:
      - "3307:3306"  # MySQL servisini 3307 portundan ayağa kaldır
    networks:
      - backend

networks:
  # Arka planda kullanılacak ağ tanımı
  backend:
    driver: bridge
    name: backend
